# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dda0caa6d10b23058e5278266aed87f70fa5cdca9adb96484828007b6e7d74facefc8ee55cde9ed7ddf97308399d63937e7c4b8b6a689ef8b9f3058abb212940

test:
  secret_key_base: a9423178e22a959b2a5c6ff93e4d930c2868b60706191fef57131f6e343650b698fd6f65305066f923fe23a9b4cd177aab6841da5b7f70839c8561ab4cc57d5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
